version: '3.9'

networks:
  eventflow-net:

services:
  EventFlow.api:
    image: eventflow.api
    container_name: eventflow.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/API/EventFlow.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    networks:
      - eventflow-net
    depends_on:
      - EventFlow.database

  EventFlow.database:
    container_name: eventflow.database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - eventflow-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - eventflow-net

volumes:
  eventflow-postgres: